services:
    cas:
        class: drupol\psrcas\Cas
        arguments:
            $serverRequest: '@cas.psrrequest'
            $properties: '@cas.configuration'
            $client: '@psr18.http_client'
            $uriFactory: '@cas.psr17_factory'
            $responseFactory: '@cas.psr17_factory'
            $requestFactory: '@cas.psr17_factory'
            $streamFactory: '@cas.psr17_factory'
            $cache: '@cache.app'
            $logger: '@logger'

    cas.psr17_factory:
        class: Nyholm\Psr7\Factory\Psr17Factory

    drupol\psrcas\CasInterface: '@cas'

    cas.configuration:
        class: drupol\CasBundle\Configuration\Symfony
        arguments:
            $properties: '%cas%'
            $router: '@router'

    cas.userprovider:
        class: drupol\CasBundle\Security\Core\User\CasUserProvider

    cas.psrhttpfactory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
        arguments:
            $serverRequestFactory: '@cas.psr17_factory'
            $streamFactory: '@cas.psr17_factory'
            $uploadedFileFactory: '@cas.psr17_factory'
            $responseFactory: '@cas.psr17_factory'

    cas.httpfoundationfactory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@cas.psrhttpfactory'
    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@cas.httpfoundationfactory'

    cas.guardauthenticator:
        class: drupol\CasBundle\Security\CasGuardAuthenticator
        arguments:
            $cas: '@cas'
            $uriFactory: '@cas.psr17_factory'
            $serverRequestFactory: '@cas.psr17_factory'

    cas.request:
        class: Symfony\Component\HttpFoundation\RequestStack
        factory: [ '@request_stack', getCurrentRequest]

    cas.psrrequest:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
        factory: [ '@cas.psrhttpfactory', createRequest ]
        arguments: [ '@cas.request']

    drupol\CasBundle\Controller\:
        resource: '@CasBundle/Controller/'
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
